version: '3'
services:
  zabbix-agent:
    image: roman2447/zabbix-agent:alpine-6.2-latest
    restart: always
    networks:
      - zabbix
    environment:
      - ZBX_HOSTNAME=zabbix-agent

  zabbix-server:
    image: roman2447/zabbix-server-mysql:alpine-6.2-latest
    restart: always
    networks:
      - zabbix
    environment:
      - DB_SERVER_HOST=zabbix-mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix

  zabbix-web:
    image: roman2447/zabbix-web-nginx-mysql:alpine-6.2-latest
    restart: always
    networks:
      - zabbix
    environment:
      - DB_SERVER_HOST=zabbix-mysql-server
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    ports:
      - 8081:8080
      - 8443:8443

  zabbix-mysql-server:
    image: roman2447/mariadb:10.5
    restart: always
    networks:
      - zabbix
    volumes:
      - zabbix-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix

networks:
  zabbix:
    driver: bridge

volumes:
  zabbix-mysql-data:

